INSERT INTO STUDENTS (NUM_Z, NAME, LAST_NAME) VALUES (109208, 'EUGENE', 'POLYAKOV');

INSERT INTO STUDENTS (NUM_Z, NAME, LAST_NAME) VALUES (209132, 'Roman', 'Moiseev');

INSERT INTO STUDENTS (NUM_Z, NAME, LAST_NAME) VALUES (200212, 'Dasha', 'Mironova');

INSERT INTO PROFESSOR (ITN, NAME, LAST_NAME) VALUES (112039945, 'Vladimir', 'Solovyev');

INSERT INTO PROFESSOR (ITN, NAME, LAST_NAME) VALUES (122345632, 'Lyudmila', 'Zinchenko');

INSERT INTO PROFESSOR (ITN, NAME, LAST_NAME) VALUES (450289751, 'Timur', 'Fathutdinov');

INSERT INTO DISCIPLINES (NAME) values ('ОКП');

INSERT INTO DISCIPLINES (NAME) values ('ФЛИТА');

INSERT INTO DISCIPLINES (NAME) values ('ТОКиН');

INSERT INTO DISCIPLINES (NAME) values ('ИССАПР');

INSERT INTO DISCIPLINES (NAME) VALUES ('КТБД');

INSERT INTO DISCIPLINES_PROFESSORS (DISCIPLINE_ID, PROFESSOR_ID)
VALUES (2, 2);

INSERT INTO DISCIPLINES_PROFESSORS (DISCIPLINE_ID, PROFESSOR_ID)
VALUES (3, 1);

INSERT INTO DISCIPLINES_PROFESSORS (DISCIPLINE_ID, PROFESSOR_ID)
VALUES (5, 3);

INSERT INTO TOPIC (NAME, DATA) 
VALUES('Введение в Git', TO_TIMESTAMP('06-FEB-24 10:15:00 AM'));

INSERT INTO TOPIC (NAME, DATA) 
VALUES('Метод конечных элементов', TO_TIMESTAMP('13-MAR-24 08:30:00 AM'));

INSERT INTO TOPIC (NAME, DATA) 
VALUES('Воздействия вибрации', TO_TIMESTAMP('12-OCT-23 09:00:00 AM'));


INSERT INTO ATTENDANCE (DISC_PROF_ID, STUDENT_ID, TOPIC_ID)
VALUES (2, 21, 3);

INSERT INTO ATTENDANCE (DISC_PROF_ID, STUDENT_ID, TOPIC_ID)
VALUES (2, 22, 3);

INSERT INTO ATTENDANCE (DISC_PROF_ID, STUDENT_ID, TOPIC_ID)
VALUES (2, 23, 3);

INSERT INTO ATTENDANCE (DISC_PROF_ID, STUDENT_ID, TOPIC_ID)
VALUES (1, 21, 2);

INSERT INTO ATTENDANCE (DISC_PROF_ID, STUDENT_ID, TOPIC_ID)
VALUES (1, 22, 2);

SELECT D.NAME as Discipline, P.NAME as Professor_Name, P.LAST_NAME as Professor_Last_name 
FROM DISCIPLINES_PROFESSORS DP JOIN DISCIPLINES D 
ON DP.DISCIPLINE_ID=D.ID JOIN PROFESSOR P ON DP.PROFESSOR_ID=P.ID